/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Movie } from "./store";
export namespace Components {
    interface MovieListItem {
        "movie": Movie;
    }
    interface MoviesList {
    }
    interface NewMovieForm {
    }
}
declare global {
    interface HTMLMovieListItemElement extends Components.MovieListItem, HTMLStencilElement {
    }
    var HTMLMovieListItemElement: {
        prototype: HTMLMovieListItemElement;
        new (): HTMLMovieListItemElement;
    };
    interface HTMLMoviesListElement extends Components.MoviesList, HTMLStencilElement {
    }
    var HTMLMoviesListElement: {
        prototype: HTMLMoviesListElement;
        new (): HTMLMoviesListElement;
    };
    interface HTMLNewMovieFormElement extends Components.NewMovieForm, HTMLStencilElement {
    }
    var HTMLNewMovieFormElement: {
        prototype: HTMLNewMovieFormElement;
        new (): HTMLNewMovieFormElement;
    };
    interface HTMLElementTagNameMap {
        "movie-list-item": HTMLMovieListItemElement;
        "movies-list": HTMLMoviesListElement;
        "new-movie-form": HTMLNewMovieFormElement;
    }
}
declare namespace LocalJSX {
    interface MovieListItem {
        "movie"?: Movie;
    }
    interface MoviesList {
    }
    interface NewMovieForm {
    }
    interface IntrinsicElements {
        "movie-list-item": MovieListItem;
        "movies-list": MoviesList;
        "new-movie-form": NewMovieForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "movie-list-item": LocalJSX.MovieListItem & JSXBase.HTMLAttributes<HTMLMovieListItemElement>;
            "movies-list": LocalJSX.MoviesList & JSXBase.HTMLAttributes<HTMLMoviesListElement>;
            "new-movie-form": LocalJSX.NewMovieForm & JSXBase.HTMLAttributes<HTMLNewMovieFormElement>;
        }
    }
}
