/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MovieListItem {
        "movie": { title: string, isEditing: boolean };
    }
    interface MoviesList {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NewMovieForm {
    }
}
declare global {
    interface HTMLMovieListItemElement extends Components.MovieListItem, HTMLStencilElement {
    }
    var HTMLMovieListItemElement: {
        prototype: HTMLMovieListItemElement;
        new (): HTMLMovieListItemElement;
    };
    interface HTMLMoviesListElement extends Components.MoviesList, HTMLStencilElement {
    }
    var HTMLMoviesListElement: {
        prototype: HTMLMoviesListElement;
        new (): HTMLMoviesListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNewMovieFormElement extends Components.NewMovieForm, HTMLStencilElement {
    }
    var HTMLNewMovieFormElement: {
        prototype: HTMLNewMovieFormElement;
        new (): HTMLNewMovieFormElement;
    };
    interface HTMLElementTagNameMap {
        "movie-list-item": HTMLMovieListItemElement;
        "movies-list": HTMLMoviesListElement;
        "my-component": HTMLMyComponentElement;
        "new-movie-form": HTMLNewMovieFormElement;
    }
}
declare namespace LocalJSX {
    interface MovieListItem {
        "movie"?: { title: string, isEditing: boolean };
    }
    interface MoviesList {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NewMovieForm {
    }
    interface IntrinsicElements {
        "movie-list-item": MovieListItem;
        "movies-list": MoviesList;
        "my-component": MyComponent;
        "new-movie-form": NewMovieForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "movie-list-item": LocalJSX.MovieListItem & JSXBase.HTMLAttributes<HTMLMovieListItemElement>;
            "movies-list": LocalJSX.MoviesList & JSXBase.HTMLAttributes<HTMLMoviesListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "new-movie-form": LocalJSX.NewMovieForm & JSXBase.HTMLAttributes<HTMLNewMovieFormElement>;
        }
    }
}
